# -*- coding: utf-8 -*-
"""tab_transformer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/expanded-nebula-754/locations/us-central1/repositories/bddd370d-1e9d-4af0-8f3d-2e8112ffa794
"""

!pip install datasets
!pip uninstall -y protobuf grpcio grpcio-status

!pip install protobuf==3.20.3 grpcio==1.53.1 grpcio-status==1.48.2

from google.cloud import storage
import os



# Setup
GCS_BUCKET = 'cdow'
GCS_FOLDER = 'leads_env'
LOCAL_BASE = f"/content/{GCS_FOLDER}"
HF_CACHE = f"{LOCAL_BASE}/hf_cache"
WHEELS_PATH = f"{LOCAL_BASE}/wheels"
REQ_PATH = f"{LOCAL_BASE}/requirements.txt"


os.makedirs(HF_CACHE, exist_ok=True)
os.makedirs(WHEELS_PATH, exist_ok=True)

client = storage.Client()
bucket = client.bucket(GCS_BUCKET)

# Download requirements.txt
blob = bucket.blob(f'{GCS_FOLDER}/requirements.txt')
blob.download_to_filename(REQ_PATH)

print(' Found and downloaded requirements.txt')



# Download wheels
for blob in bucket.list_blobs(prefix=f'{GCS_FOLDER}/wheels'):
    relative_path = blob.name.replace(f'{GCS_FOLDER}/', '')  # Strip GCS_FOLDER prefix
    local_path = os.path.join(LOCAL_BASE, relative_path)
    os.makedirs(os.path.dirname(local_path), exist_ok=True)
    blob.download_to_filename(local_path)
print('Wheels downloaded')

# Download Hugging Face model files
for blob in bucket.list_blobs(prefix=f'{GCS_FOLDER}/hf_cache'):
    relative_path = blob.name.replace(f'{GCS_FOLDER}/', '')
    local_path = os.path.join(LOCAL_BASE, relative_path)
    os.makedirs(os.path.dirname(local_path), exist_ok=True)
    blob.download_to_filename(local_path)
print(' Hugging Face model files downloaded')

!pip install --no-index --find-links={WHEELS_PATH} -r {REQ_PATH}


import os
import re

import sys
from tqdm import tqdm
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from datasets import Dataset
from tab_transformer_pytorch import TabTransformer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from collections import defaultdict
import pickle

from torch.utils.data import TensorDataset, DataLoader



import gcsfs
from itertools import islice
import gc
from datasets import load_dataset
# Initialize BigQuery client
# Set up GCS client
client = storage.Client()
bucket = client.bucket('cdow')
#print(TabTransformer)

fs = gcsfs.GCSFileSystem()

# Path to your CSV in GCS
parquet_path = 'cdow/leads_data/leads_scoring.parquet'
df = []
# Read CSV directly into a pandas DataFrame
with fs.open(f'gs://{parquet_path}') as f:
    df = pd.read_parquet(f)

print(df.columns[0])
print(df.columns[3])
print(df.columns[4])
print(df.columns[5])
print(df.columns[8])
print(df.columns[15])

df_categories = df[[df.columns[0],df.columns[3],df.columns[4],df.columns[5],df.columns[15]]]
print(df_categories.head())
print(df_categories.dtypes)

max_list_lengths = {}
print(df_categories.columns)
for col in df_categories.columns[1:-1]:
    if df_categories[col].apply(lambda x: isinstance(x, list) or isinstance(x, object)).any():
        max_length = df_categories[col].apply(lambda x: len(x) if isinstance(x, list) or isinstance(x, object)  else 0).max()
        max_list_lengths[col] = max_length

for col, length in max_list_lengths.items():
    print(f"{col}: {length}")

print(len(df_categories))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

for col in df_categories.columns[:-1]:
    dtype = df_categories[col].dtype
    if pd.api.types.is_string_dtype(dtype) or dtype == object:
        df_categories.loc[:, col] = df_categories[col].fillna('')

print(device)

df_categories.loc[:,"country_identifier"] = df_categories["Country"].astype(str) # convert to string for encoding
df_categories.loc[:,'is_won'] = df_categories['is_won'].astype(float)

le = LabelEncoder()#.loc[:, col]
df_categories.loc[:,"country_identifier_encoded"] = le.fit_transform(df_categories["country_identifier"])
train_df, test_df = train_test_split(df_categories, test_size=0.2, random_state=42)
# Define features and label
categorical_cols = ["country_identifier_encoded"]
continuous_cols =[]
target_col = ['is_won']

def df_to_tensor(df, cat_cols, cont_cols, target_col):
    x_cat = torch.tensor(df[cat_cols].values, dtype=torch.long)
    x_cont = torch.tensor(df[cont_cols].values, dtype=torch.float) if cont_cols else None
    y = torch.tensor(df[target_col].values, dtype=torch.float)
    return x_cat, x_cont, y

x_cat_train, x_cont_train, y_train = df_to_tensor(train_df, categorical_cols, continuous_cols, target_col)
x_cat_test, x_cont_test, y_test = df_to_tensor(test_df, categorical_cols, continuous_cols, target_col)

#x_cat_train,  y_train = df_to_tensor(train_df, categorical_cols,  target_col)
#x_cat_test,  y_test = df_to_tensor(test_df, categorical_cols,  target_col)


x_cat_train = x_cat_train.to(device)
#x_cont_train = x_cont_train.to(device) if x_cont_train is not None else None
x_cont_train = torch.empty((x_cat_train.shape[0], 0), dtype=torch.float).to(device)
y_train = y_train.to(device)

x_cat_test = x_cat_test.to(device)
x_cont_test = x_cont_test.to(device) if x_cont_test is not None else None
y_test = y_test.to(device)


train_dataset = TensorDataset(x_cat_train, x_cont_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)


model = TabTransformer(
    categories = [len(le.classes_)], # number of unique promo_identifiers
    num_continuous = 0,#len(continuous_cols),
    dim = 32,
    depth = 6,
    heads = 8,
    attn_dropout = 0.1,
    ff_dropout = 0.1,
    mlp_hidden_mults = (4, 2),
    mlp_act = nn.ReLU()
)
model = model.to(device)
model.train()

criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)


epochs = 10
for epoch in range(epochs):
    model.train()
    total_loss = 0

    for x_cat_batch, x_cont_batch, y_batch in train_loader:
        x_cat_batch = x_cat_batch.to(device)
        x_cont_batch = x_cont_batch.to(device)
        #y_batch = y_batch.to(device)


        y_batch = y_batch.to(device).squeeze()

        optimizer.zero_grad()
        logits = model(x_cat_batch, x_cont_batch).squeeze()
        loss = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.4f}")




#continuous_cols = [] # add other numerical features here if you have any
#target_col = "is_converted"

# === Define and Train TabTransformer ===
#model = TabTransformer(
#    categories=category_dims,
#    num_continuous=num_continuous,
#    dim=32,
#    depth=4,
#    heads=4,
#    attn_dropout=0.1,
#    ff_dropout=0.1,
#    mlp_hidden_mults=(4, 2),
#    mlp_act=torch.nn.ReLU()
#)

#optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
#loss_fn = torch.nn.BCELoss()

#for epoch in range(10):
#    model.train()
#    prob = nn.sigmoid(model(X_cat, X_cont).squeeze())
#    loss = loss_fn(logits, y.float())
#    loss.backward()
#    optimizer.step()
#    optimizer.zero_grad()
#    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

# === Save Model and Metadata ===
#torch.save(model.state_dict(), "tabtransformer.pt")
#with open("tabtransformer_meta.pkl", "wb") as f:
#    pickle.dump({
#        "category_dims": category_dims,
#        "num_continuous": num_continuous
#    }, f)